name: Fetch News

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  fetch-news:
    if: github.ref == 'refs/heads/main'  # Extra check to ensure it only runs on main
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main  # Explicitly checkout main branch
    
    - name: Print LC_CTYPE
      run: |
        echo "LC_CTYPE=$LC_CTYPE"
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    #LC_CTYPE
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers  
      run: playwright install
        
    - name: Run news fetcher
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python -m getArticles.postNews