name: Fetch News (Trigger)

on:
  schedule:
    - cron: "*/20 * * * *"  # Every 20 minutes
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-news-fetch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger News Fetch workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Fetch News (Fetcher)
          ref: main
          token: ${{ secrets.ACTIONS_PAT }}