name: Fetch News (Fetcher)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Fetch News (Trigger)"]
    types:
      - requested

defaults:
  run:
    working-directory: .

jobs:
  fetch-news:
    # Removed the if: condition, as it's now guaranteed to be on main
    runs-on: ubuntu-latest
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  # Still good practice

      - name: Print locale variables
        run: |
          echo "LC_ALL=$LC_ALL"
          echo "LANG=$LANG"
          echo "LC_CTYPE=$LC_CTYPE"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install

      - name: Run news fetcher
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DEBUG_ASCII: "false"
        run: python -m getArticles.postNews