name: Post News Workflow

on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  post-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Show Crawl4AI Version
      run: |
        pip show crawl4ai
        python -c "import crawl4ai; print('Crawl4AI Version:', crawl4ai.__version__)"
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install --with-deps
        
    - name: Run postNews script
      run: python -m getArticles.postNews
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        # Add any other environment variables your script needs