name: Sequential Pipeline (Trigger)

on:
  schedule:
    - cron: "0 */1 * * *"  # Every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-pipeline:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sequential Pipeline workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: run-sequential-pipeline
          token: ${{ secrets.ACTIONS_PAT }}