name: Combined Workflow Trigger

on:
  schedule:
    - cron: "*/20 * * * *"  # For news fetch (every 20 minutes)
    - cron: "0 */1 * * *"   # For pipeline (every hour)
    - cron: "0 */2 * * *"   # For article status update (every 2 hours)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-workflows:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger News Fetch workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: fetch_news.yml
          ref: main
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Trigger Sequential Pipeline workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run Sequential Pipeline (Fetcher)
          ref: main
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Trigger Article Status Update workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Article Statuses
          ref: main
          token: ${{ secrets.ACTIONS_PAT }}